### ISSUE TITLE
Server demo not starting

### ISSUE THREAD

**Issue by binuraj-rs** [casinthecloud/cas-pac4j-oauth-demo#36]
I have downloaded the master version and tried out. The build was success and run the two applications. The Client demo application is starting successfully. But the cas server application not starting.  This is the last log I found in my command window.

@2017-05-11 14:32:36,360 INFO [org.apereo.cas.services.DefaultServicesManagerImpl
] - <Loaded 5 services from JsonServiceRegistryDao.>

This log is repeating 5 times with in a minute.  Please help me to solve the issue.

**Comment by leleuj** [comment]
I don't think this log is relevant: it just says that it reloads the CAS services every x seconds. What are you referring to as a CAS server application? I think you should have more meaningful logs somewhere...
