### ISSUE TITLE
CAS server does not come out in the Web browser

### ISSUE THREAD

**Issue by aaguerra** [casinthecloud/cas-pac4j-oauth-demo#38]
The CAS server successfully starts

There is no error, but when you go to the browser to the URL _ http://localhost:8081/cas2 Nothing appears or generates error in the log

Attachment log File

[log.txt](https://github.com/casinthecloud/cas-pac4j-oauth-demo/files/1192529/log.txt)

**Comment by leleuj** [comment]
It's `http://localhost:8081/cas` and not `http://localhost:8081/cas2` (https://github.com/casinthecloud/cas-pac4j-oauth-demo/blob/master/cas-pac4j-oauth-server-demo/src/main/resources/application.properties#L5)
